// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var persisto = persisto || {};

/**
 * @const
 * @namespace
 */
persisto.proto = persisto.proto || {};

/**
 * @const
 * @namespace
 */
persisto.proto.message = persisto.proto.message || {};

/**
 * @constructor
 */
persisto.proto.message.Message = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {persisto.proto.message.Message}
 */
persisto.proto.message.Message.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {persisto.proto.message.Message=} obj
 * @returns {persisto.proto.message.Message}
 */
persisto.proto.message.Message.getRootAsMessage = function(bb, obj) {
  return (obj || new persisto.proto.message.Message).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
persisto.proto.message.Message.prototype.content = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
persisto.proto.message.Message.prototype.receiver = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
persisto.proto.message.Message.prototype.sender = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
persisto.proto.message.Message.startMessage = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} contentOffset
 */
persisto.proto.message.Message.addContent = function(builder, contentOffset) {
  builder.addFieldOffset(0, contentOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} receiver
 */
persisto.proto.message.Message.addReceiver = function(builder, receiver) {
  builder.addFieldInt32(1, receiver, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sender
 */
persisto.proto.message.Message.addSender = function(builder, sender) {
  builder.addFieldInt32(2, sender, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
persisto.proto.message.Message.endMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
persisto.proto.message.Message.finishMessageBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.persisto = persisto;
